//Created by Action Script Viewer - http://www.buraks.com/asv
package 
{
    import flash.display.Sprite;
    import model.LogApplication;
    import model.XxteaEncodeAndDecode;
    import zebra.Game;
    import model.WebParamModel;
    import model.BidStageUserModel;
    import model.BidStageServerModel;
    import model.BidInfoServerModel;
    import view.BrowserPart;
    import flash.external.ExternalInterface;

    public class Main extends Sprite 
    {

        public static var isKickOut:Boolean = false;
        public static var clientui_version:String = "版本:1.6.19.2";

        public var logappliction1:LogApplication;
        public var xxtea1:XxteaEncodeAndDecode;
        public var passCheck:Boolean = true;

        public function Main()
        {
            this.logappliction1 = new LogApplication();
            this.xxtea1 = new XxteaEncodeAndDecode();
            super();
            new Game(stage);
            Game.Hack.keepframe();
            var webParamMode:WebParamModel = new WebParamModel();
            var uid:String = stage.loaderInfo.parameters["uid"];
            webParamMode.uid = uid;
            var username:String = stage.loaderInfo.parameters["uname"];
            webParamMode.username = username;
            var clientid:String = stage.loaderInfo.parameters["clientId"];
            webParamMode.clientid = clientid;
            var left_socketIPList:String = stage.loaderInfo.parameters["informationserverstr"];
            webParamMode.left_socketIPList = left_socketIPList;
            var right_socketIPList:String = stage.loaderInfo.parameters["tradeserverstr"];
            webParamMode.right_socketIPList = right_socketIPList;
            var httpIP:String = stage.loaderInfo.parameters["webserverstr"];
            webParamMode.httpIP = httpIP.split(",")[0];
            var logIP:String = stage.loaderInfo.parameters["lcserverstr"];
            webParamMode.logIP = logIP;
            var userModel:BidStageUserModel = new BidStageUserModel();
            userModel.bidnumber = webParamMode.uid;
            userModel.clientId = webParamMode.clientid;
            trace("BidStageUserModel初始化");
            var bidStageServerModel:BidStageServerModel = new BidStageServerModel();
            bidStageServerModel.iplist = this.parseIpList(webParamMode.right_socketIPList);
            bidStageServerModel.bootIP = bidStageServerModel.iplist[0];
            var bidInfoModel:BidInfoServerModel = new BidInfoServerModel();
            bidInfoModel.iplist = this.parseIpList(webParamMode.left_socketIPList);
            bidInfoModel.bootIP = bidInfoModel.iplist[0];
            addChild(new BrowserPart());
            var setUserInfo:* = ExternalInterface.call("showCusInfo", webParamMode.username, webParamMode.uid);
        }

        private function parseIpList(iplist:String):Array
        {
            var arr:Array = iplist.split(",");
            var _tempArr:Array = new Array();
            var i:int;
            while (i < arr.length)
            {
                _tempArr.push(arr[i].split(":")[0]);
                i++;
            };
            return (_tempArr);
        }


    }
}//package 
    //force all classes
    import Main; Main;
    import view.BrowserPart; view.BrowserPart;
    import model.ServerModel; model.ServerModel;
    import model.BidStageServerModel; model.BidStageServerModel;
    import zebra.Game; zebra.Game;
    import model.LogApplication; model.LogApplication;
    import zebra.core.GameModel; zebra.core.GameModel;
    import model.BidStageUserModel; model.BidStageUserModel;
    import model.XxteaEncodeAndDecode; model.XxteaEncodeAndDecode;
    import model.WebParamModel; model.WebParamModel;
    import model.BidInfoServerModel; model.BidInfoServerModel;
//     import zebra.core.BaseSprite; zebra.core.BaseSprite;
    import zebra.core.GameView; zebra.core.GameView;
    import view.BidInitView; view.BidInitView;
    import zebra.system.collections.GUID; zebra.system.collections.GUID;
    import wicresoft.errorInfo; wicresoft.errorInfo;
    import view.BidStageView; view.BidStageView;
    import ws.Kictout; ws.Kictout;
    import view.KickOutPart; view.KickOutPart;
    import zebra.directEvent.IDirectEventManager; zebra.directEvent.IDirectEventManager;
    import zebra.input.MouseInput; zebra.input.MouseInput;
    import zebra.content.GameContent; zebra.content.GameContent;
    import zebra.graphics.GraphicsDeviceManager; zebra.graphics.GraphicsDeviceManager;
    import zebra.input.KeyInput; zebra.input.KeyInput;
    import zebra.system.GameHack; zebra.system.GameHack;
    import zebra.core.GameTimeUpdate; zebra.core.GameTimeUpdate;
    import zebra.data.GameDataService; zebra.data.GameDataService;
    import zebra.system.net.GameSocketThread; zebra.system.net.GameSocketThread;
    import zebra.directEvent.DirectEventManager; zebra.directEvent.DirectEventManager;
    import ws.LogWin; ws.LogWin;
    import view.LogWinPart; view.LogWinPart;
    import util.MD5; util.MD5;
    import zebra.system.collections.ByteArrayCollection; zebra.system.collections.ByteArrayCollection;
    import util.XXTEA; util.XXTEA;
    import util.Base64; util.Base64;
    import view.BidInfoView; view.BidInfoView;
    import ws.WarnInfo; ws.WarnInfo;
    import view.WarnInfoPart; view.WarnInfoPart;
    import util.BidInfoParse; util.BidInfoParse;
    import control.PriceParseControl; control.PriceParseControl;
    import zebra.system.collections.ByteArrayReader; zebra.system.collections.ByteArrayReader;
    import zebra.system.collections.FlashBytesReader; zebra.system.collections.FlashBytesReader;
    import zebra.directEvent.DirectEventParameter; zebra.directEvent.DirectEventParameter;
    import zebra.system.net.SocketThreadParam; zebra.system.net.SocketThreadParam;
    import model.UserQueue; model.UserQueue;
    import ws.PriceResult2; ws.PriceResult2;
    import view.PriceWaitPart; view.PriceWaitPart;
    import control.SocketControl; control.SocketControl;
    import view.BidStagePart; view.BidStagePart;
    import zebra.thread.task.ITaskAction; zebra.thread.task.ITaskAction;
    import zebra.thread.task.TaskAction; zebra.thread.task.TaskAction;
    import task.BidStageHeartAction; task.BidStageHeartAction;
    import zebra.system.util.Javascript; zebra.system.util.Javascript;
//     import zebra.input.MouseInputTaskAction; zebra.input.MouseInputTaskAction;
    import zebra.events.TaskActionEvent; zebra.events.TaskActionEvent;
    import zebra.events.GameMouseEvent; zebra.events.GameMouseEvent;
//     import zebra.content.GameContentItem; zebra.content.GameContentItem;
//     import zebra.content.GameModelContent; zebra.content.GameModelContent;
//     import zebra.content.GameAssetLoaderContent; zebra.content.GameAssetLoaderContent;
//     import zebra.content.GameSingleClass; zebra.content.GameSingleClass;
    import zebra.loaders.IAssetLoader; zebra.loaders.IAssetLoader;
//     import zebra.content.ObjectContent; zebra.content.ObjectContent;
    import zebra.system.util.FlashCookie; zebra.system.util.FlashCookie;
//     import zebra.content.GameViewContent; zebra.content.GameViewContent;
    import zebra.graphics.animation.BitmapBatchManager; zebra.graphics.animation.BitmapBatchManager;
    import zebra.input.KeyInputData; zebra.input.KeyInputData;
    import zebra.events.KeyInputEvent; zebra.events.KeyInputEvent;
//     import zebra.input.KeyInputTaskAction; zebra.input.KeyInputTaskAction;
    import zebra.system.net.IGameSocket; zebra.system.net.IGameSocket;
//     import zebra.system.net.GameSocketManager; zebra.system.net.GameSocketManager;
    import zebra.directEvent.DirectEventScope; zebra.directEvent.DirectEventScope;
//     import zebra.directEvent.DirectEventDestroyPool; zebra.directEvent.DirectEventDestroyPool;
//     import zebra.directEvent.DirectEventSendAction; zebra.directEvent.DirectEventSendAction;
//     import zebra.directEvent.DirectEventListenerPool; zebra.directEvent.DirectEventListenerPool;
    import Button_selectedUpSkin; Button_selectedUpSkin;
    import fl.core.ComponentShim; fl.core.ComponentShim;
    import Button_emphasizedSkin; Button_emphasizedSkin;
    import ScrollArrowDown_overSkin; ScrollArrowDown_overSkin;
    import Button_disabledSkin; Button_disabledSkin;
    import Button_overSkin; Button_overSkin;
    import ScrollBar_thumbIcon; ScrollBar_thumbIcon;
    import Button_selectedOverSkin; Button_selectedOverSkin;
    import focusRectSkin; focusRectSkin;
    import ScrollArrowUp_overSkin; ScrollArrowUp_overSkin;
    import ScrollArrowDown_upSkin; ScrollArrowDown_upSkin;
    import fl.core.UIComponent; fl.core.UIComponent;
    import fl.controls.BaseButton; fl.controls.BaseButton;
    import fl.managers.IFocusManagerComponent; fl.managers.IFocusManagerComponent;
    import fl.controls.LabelButton; fl.controls.LabelButton;
    import fl.controls.Button; fl.controls.Button;
    import ScrollThumb_upSkin; ScrollThumb_upSkin;
    import ScrollArrowUp_disabledSkin; ScrollArrowUp_disabledSkin;
    import ScrollTrack_skin; ScrollTrack_skin;
    import ScrollArrowDown_disabledSkin; ScrollArrowDown_disabledSkin;
    import ScrollArrowUp_upSkin; ScrollArrowUp_upSkin;
    import Button_selectedDisabledSkin; Button_selectedDisabledSkin;
    import ScrollThumb_downSkin; ScrollThumb_downSkin;
    import fl.controls.ScrollBar; fl.controls.ScrollBar;
    import fl.controls.UIScrollBar; fl.controls.UIScrollBar;
    import ScrollArrowUp_downSkin; ScrollArrowUp_downSkin;
    import Button_upSkin; Button_upSkin;
    import TextArea_upSkin; TextArea_upSkin;
    import Button_selectedDownSkin; Button_selectedDownSkin;
    import fl.controls.TextArea; fl.controls.TextArea;
    import Button_downSkin; Button_downSkin;
    import ScrollThumb_overSkin; ScrollThumb_overSkin;
    import TextArea_disabledSkin; TextArea_disabledSkin;
    import ScrollArrowDown_downSkin; ScrollArrowDown_downSkin;
    import util.IntUtil; util.IntUtil;
    import zebra.system.util.SocketServerType; zebra.system.util.SocketServerType;
    import model.BidInfoUserModel; model.BidInfoUserModel;
    import ws.Bidinfo; ws.Bidinfo;
    import view.BidInfoPart; view.BidInfoPart;
    import task.BidInfoWebDataAction; task.BidInfoWebDataAction;
    import task.BidInfoHeartAction; task.BidInfoHeartAction;
    import event.InfoTagEvent; event.InfoTagEvent;
    import ws.Loader; ws.Loader;
    import ws.PriceInfoWindow; ws.PriceInfoWindow;
    import view.PriceInfoWindowPart; view.PriceInfoWindowPart;
    import ws.BidStage; ws.BidStage;
    import ws.SelfTopPriceWindow; ws.SelfTopPriceWindow;
    import view.SelfTopPriceWindowPart; view.SelfTopPriceWindowPart;
    import zebra.thread.task.Task; zebra.thread.task.Task;
    import zebra.loaders.ILoader; zebra.loaders.ILoader;
    import zebra.events.BitmapBatchEvent; zebra.events.BitmapBatchEvent;
    import zebra.graphics.animation.IAnimation; zebra.graphics.animation.IAnimation;
    import zebra.graphics.animation.BitmapBatch; zebra.graphics.animation.BitmapBatch;
    import zebra.events.GameSocketEvent; zebra.events.GameSocketEvent;
//     import zebra.system.net.SocketBufferAction; zebra.system.net.SocketBufferAction;
    import zebra.system.util.SocketPackUtil; zebra.system.util.SocketPackUtil;
    import zebra.directEvent.DirectEventAction; zebra.directEvent.DirectEventAction;
    import fl.managers.IFocusManager; fl.managers.IFocusManager;
    import fl.managers.FocusManager; fl.managers.FocusManager;
    import fl.managers.StyleManager; fl.managers.StyleManager;
    import fl.core.InvalidationType; fl.core.InvalidationType;
    import fl.events.ComponentEvent; fl.events.ComponentEvent;
    import fl.controls.ButtonLabelPlacement; fl.controls.ButtonLabelPlacement;
    import fl.events.ScrollEvent; fl.events.ScrollEvent;
    import fl.controls.ScrollBarDirection; fl.controls.ScrollBarDirection;
    import fl.controls.ScrollPolicy; fl.controls.ScrollPolicy;
    import zebra.content.GameAsset; zebra.content.GameAsset;
    import wicresot.Subtract300; wicresot.Subtract300;
    import ws.Price; ws.Price;
    import wicresoft.background; wicresoft.background;
    import ws.peoplePriceInfoButton; ws.peoplePriceInfoButton;
    import ws.Price2; ws.Price2;
    import zebra.events.TaskEvent; zebra.events.TaskEvent;
    import zebra.events.AssetLoaderEvent; zebra.events.AssetLoaderEvent;
    import zebra.graphics.bitmaps.BitmapDataTool; zebra.graphics.bitmaps.BitmapDataTool;
    import fl.managers.IFocusManagerGroup; fl.managers.IFocusManagerGroup;
    import zebra.loaders.AssetLoader; zebra.loaders.AssetLoader;
//     import zebra.content.GameAssetLoadLogic; zebra.content.GameAssetLoadLogic;
    import zebra.loaders.AssetType; zebra.loaders.AssetType;
    import zebra.graphics.bitmaps.BitmapDataDraw; zebra.graphics.bitmaps.BitmapDataDraw;
    import zebra.loaders.AssetBaseLoader; zebra.loaders.AssetBaseLoader;
    import zebra.loaders.AssetTextLoader; zebra.loaders.AssetTextLoader;
    import zebra.loaders.AssetLoaderAction; zebra.loaders.AssetLoaderAction;
    import zebra.debug.Debug; zebra.debug.Debug;
    import zebra.loaders.AssetDisplayLoader; zebra.loaders.AssetDisplayLoader;
    import zebra.loaders.AssetLoaderState; zebra.loaders.AssetLoaderState;
    import zebra.system.reflection.Reflection; zebra.system.reflection.Reflection;
    import zebra.system.reflection.ReflectionMember; zebra.system.reflection.ReflectionMember;
    import zebra.system.reflection.StaticMethod; zebra.system.reflection.StaticMethod;
    import zebra.system.reflection.Accessor; zebra.system.reflection.Accessor;
    import zebra.system.reflection.Variable; zebra.system.reflection.Variable;
    import zebra.system.reflection.StaticAccessor; zebra.system.reflection.StaticAccessor;
    import zebra.system.reflection.Constant; zebra.system.reflection.Constant;
    import zebra.system.reflection.Method; zebra.system.reflection.Method;
    import zebra.system.reflection.StaticConstant; zebra.system.reflection.StaticConstant;
    import zebra.system.reflection.StaticVariable; zebra.system.reflection.StaticVariable;
//     import zebra.system.reflection.ReflectionDescribeTypePool; zebra.system.reflection.ReflectionDescribeTypePool;
    import zebra.system.reflection.StaticMethodInfo; zebra.system.reflection.StaticMethodInfo;
    import zebra.system.reflection.StaticMethodParameterInfo; zebra.system.reflection.StaticMethodParameterInfo;
    import zebra.system.reflection.AccessorInfo; zebra.system.reflection.AccessorInfo;
    import zebra.system.reflection.VariableInfo; zebra.system.reflection.VariableInfo;
    import zebra.system.reflection.StaticAccessorInfo; zebra.system.reflection.StaticAccessorInfo;
    import zebra.system.reflection.ConstantInfo; zebra.system.reflection.ConstantInfo;
    import zebra.system.reflection.MethodParameterInfo; zebra.system.reflection.MethodParameterInfo;
    import zebra.system.reflection.MethodInfo; zebra.system.reflection.MethodInfo;
    import zebra.system.reflection.StaticConstantInfo; zebra.system.reflection.StaticConstantInfo;
    import zebra.system.reflection.StaticVariableInfo; zebra.system.reflection.StaticVariableInfo;
